export interface BankOption {
  value: string;
  label: string;
}

export const NIGERIAN_BANKS: BankOption[] = [
  { value: 'Access Bank', label: 'Access Bank' },
  { value: 'Access Bank (Diamond)', label: 'Access Bank (Diamond)' },
  { value: 'ALAT by Wema', label: 'ALAT by Wema' },
  { value: 'Amju Unique MFB', label: 'Amju Unique MFB' },
  { value: 'Bainescredit MFB', label: 'Bainescredit MFB' },
  { value: 'Bowen Microfinance Bank', label: 'Bowen Microfinance Bank' },
  { value: 'Carbon', label: 'Carbon' },
  { value: 'CEMCS Microfinance Bank', label: 'CEMCS Microfinance Bank' },
  { value: 'Citi Bank', label: 'Citi Bank' },
  { value: 'Coronation Merchant Bank', label: 'Coronation Merchant Bank' },
  { value: 'Covenant Microfinance Bank', label: 'Covenant Microfinance Bank' },
  { value: 'Dot Microfinance Bank', label: 'Dot Microfinance Bank' },
  { value: 'Easyby Zenith', label: 'Easyby Zenith' },
  { value: 'Ecobank Nigeria', label: 'Ecobank Nigeria' },
  { value: 'Ekondo Microfinance Bank', label: 'Ekondo Microfinance Bank' },
  { value: 'Eyowo', label: 'Eyowo' },
  { value: 'FairMoney Microfinance Bank', label: 'FairMoney Microfinance Bank' },
  { value: 'Fidelity Bank', label: 'Fidelity Bank' },
  { value: 'First Bank of Nigeria', label: 'First Bank of Nigeria' },
  { value: 'First City Monument Bank (FCMB)', label: 'First City Monument Bank (FCMB)' },
  { value: 'FSDH Merchant Bank Limited', label: 'FSDH Merchant Bank Limited' },
  { value: 'Globus Bank', label: 'Globus Bank' },
  { value: 'Guaranty Trust Bank (GTB)', label: 'Guaranty Trust Bank (GTB)' },
  { value: 'Hackman Microfinance Bank', label: 'Hackman Microfinance Bank' },
  { value: 'Hasal Microfinance Bank', label: 'Hasal Microfinance Bank' },
  { value: 'Heritage Bank', label: 'Heritage Bank' },
  { value: 'HopePSB', label: 'HopePSB' },
  { value: 'Ibile Microfinance Bank', label: 'Ibile Microfinance Bank' },
  { value: 'Ikoyi Osun MFB', label: 'Ikoyi Osun MFB' },
  { value: 'Jaiz Bank', label: 'Jaiz Bank' },
  { value: 'Kaduna Microfinance Bank', label: 'Kaduna Microfinance Bank' },
  { value: 'KeyStone Bank', label: 'KeyStone Bank' },
  { value: 'Kuda Bank (Kuda MFB)', label: 'Kuda Bank (Kuda MFB)' },
  { value: 'Links MFB', label: 'Links MFB' },
  { value: 'Lotus Bank', label: 'Lotus Bank' },
  { value: 'Mayfair MFB', label: 'Mayfair MFB' },
  { value: 'Mint Finex MFB / Mintyn', label: 'Mint Finex MFB / Mintyn' },
  { value: 'Moniepoint Microfinance Bank', label: 'Moniepoint Microfinance Bank' },
  { value: 'Mutual Trust Microfinance Bank', label: 'Mutual Trust Microfinance Bank' },
  { value: 'OPay Digital Services', label: 'OPay Digital Services' },
  { value: 'OPTIMUS Bank', label: 'OPTIMUS Bank' },
  { value: 'Paga', label: 'Paga' },
  { value: 'PalmPay', label: 'PalmPay' },
  { value: 'Parallex Bank', label: 'Parallex Bank' },
  { value: 'Parkland Microfinance Bank', label: 'Parkland Microfinance Bank' },
  { value: 'Paycom (OPay)', label: 'Paycom (OPay)' },
  { value: 'Polaris Bank', label: 'Polaris Bank' },
  { value: 'PremiumTrust Bank', label: 'PremiumTrust Bank' },
  { value: 'Providus Bank', label: 'Providus Bank' },
  { value: 'QuickFund MFB', label: 'QuickFund MFB' },
  { value: 'Rand Merchant Bank', label: 'Rand Merchant Bank' },
  { value: 'Rubies MFB', label: 'Rubies MFB' },
  { value: 'SafeHaven MFB', label: 'SafeHaven MFB' },
  { value: 'Signature Bank', label: 'Signature Bank' },
  { value: 'Sparkle Microfinance Bank', label: 'Sparkle Microfinance Bank' },
  { value: 'Stanbic IBTC Bank', label: 'Stanbic IBTC Bank' },
  { value: 'Standard Chartered Bank', label: 'Standard Chartered Bank' },
  { value: 'Sterling Bank', label: 'Sterling Bank' },
  { value: 'SunTrust Bank', label: 'SunTrust Bank' },
  { value: 'Taj Bank', label: 'Taj Bank' },
  { value: 'TCFF MFB', label: 'TCFF MFB' },
  { value: 'Titan Trust Bank', label: 'Titan Trust Bank' },
  { value: 'Unical MFB', label: 'Unical MFB' },
  { value: 'Union Bank of Nigeria', label: 'Union Bank of Nigeria' },
  { value: 'United Bank for Africa (UBA)', label: 'United Bank for Africa (UBA)' },
  { value: 'Unity Bank', label: 'Unity Bank' },
  { value: 'VFD Microfinance Bank', label: 'VFD Microfinance Bank' },
  { value: 'Wema Bank', label: 'Wema Bank' },
  { value: 'Zenith Bank', label: 'Zenith Bank' }
];
